- name: Install mailutils postfix for sending emails (provide sendmail in php, mail in console)
  apt: pkg={{ item }}
  with_items:
    - mailutils
    - postfix
  sudo: yes
-
  name: Listen only on local interface
  lineinfile: dest=/etc/postfix/main.cf regexp='^inet_interfaces' line='inet_interfaces = 127.0.0.1'
  notify: restart postfix
